# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c826a011f489d4118262d5da1463d4940f07d7ffdb4141eee17823eb11c2cb083b1298340225c9e351badd23cd7adc8a50209c834dfc21fef48965a43bb8cc1

test:
  secret_key_base: 7fd02a8c4ce53484c1fbb3dc72f77d5fbbf1b3a49cc2ca3768e1baddef734560f996b733e827bf3041855f536bffcb97e37d072086a797509aebb9ad9fa66e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
